### ISSUE TITLE
Contributor Code of Conduct

### ISSUE THREAD

**Issue by mihaiep** [mihaiep/User-Feedback-stuff#6]
this need to be reviewed:  https://github.com/mihaiep/User-Feedback-stuff/blob/master/CODE_OF_CONDUCT.md

**Comment by dshaw** [comment]
@mihaiep I think you should start by submitting the Code of Conduct. There's nothing novel to add and it will help familiarize you with the workflow. Take notes as you go. I think we need better meta docs around these processes.

Have you been able to setup a meeting with Mike? If so, try to do this with him tomorrow.

If he's not available, I should have some time after lunch and can pair with you.

**Comment by mihaiep** [comment]
Submitted. I sent an email to Mike, in the meantime I am getting more familiar with github. Cannot talk today business hours, but I'll check resources tonight.

**Comment by mihaiep** [comment]
Closed issue by mistake/reopen
